version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/healthadvocate"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

